### ISSUE TITLE
Add a trigger to debug session

### ISSUE THREAD

**Issue by lobophf** [s1n7ax/youtube-java-debugging#1]
Hi, Youtube doesn't like some keywords and links, and I decided to open this issue to explain the details. So, I had instaled the jdtls manually and I'm trying to figure out how to modify your Lua file in order to get the nvim-dap to work.
Unfortunately, I wasn't able to do that because don't know how to set it up without using nvim-lspinstall. Unlike you, In my jdtls config file, I linked the "debug plugin jar file" on bundles, inside the init_options and I'm trying to trigger my Lua file to start the debug session.

Can you help me? If you do, please see these files on my repository. Feel free to modify anything you want.
.config/nvim/init.lua 
~/.config/nvim/ftplugin/java.lua
~/.config/nvim/lua/user/nvim-dap.lua

My repository: https://github.com/lobophf/personal-nvim-config

**Comment by s1n7ax** [comment]
You have not setup any LS. You should setup JDTLS, and load the plugin to the server so that you have the additional commands such as vscode.java.startDebugSession

https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#jdtls

**Comment by lobophf** [comment]
Hi, thanks for the reply. Far as I know, my LSP is working fine because I can use code actions commands. I set it up following this page: 
https://github.com/mfussenegger/nvim-jdtls

In addition, I put the "com.microsoft.java.debug.plugin-0.36.0.jar" link in there, as you can see here.
https://github.com/lobophf/personal-nvim-config/blob/master/ftplugin/java.lua

**Comment by s1n7ax** [comment]
Where are you setting up lspconfig?

**Comment by lobophf** [comment]
I'm not sure if I understood your question, but let me detail it more.
I put these lines bellow in [here](https://github.com/lobophf/personal-nvim-config/blob/master/lua/packages.lua)
```
packer.startup(function()
  -- LSP
  use 'neovim/nvim-lspconfig'
  use 'mfussenegger/nvim-jdtls' -- java

  -- Debuging    
  use 'mfussenegger/nvim-dap'    
)
```
And I'm trying to trigger the debugger in these lines below, like you did in your tutorial, see [my version](https://github.com/lobophf/personal-nvim-config/blob/master/lua/user/nvim-dap.lua):

```
M = {}
function M.start_debug_session(callback)
    M.execute_command('vscode.java.startDebugSession', callback)
end

dap.adapters.java = function(callback)
    M.start_debug_session(
        function(port)
            callback({ type = 'server', host = '127.0.0.1', port = port })
        end)
end
``` 
My init.lula is loading these stuff above, as you can see [here](https://github.com/lobophf/personal-nvim-config/blob/master/init.lua)
```
-- Debug    
require('user.nvim-dap')
```
In addition, when I open some java file, the server starts and it should load the com.microsoft.java.debug.plugin-0.36.0.jar at line 29. See [here](https://github.com/lobophf/personal-nvim-config/blob/master/ftplugin/java.lua)
```
local config = {
  -- The command that starts the language server
  -- See: https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line
  cmd = {
    'java',
    '-Declipse.application=org.eclipse.jdt.ls.core.id1',
    '-Dosgi.bundles.defaultStartLevel=4',
    '-Declipse.product=org.eclipse.jdt.ls.core.product',
    '-Dlog.protocol=true',
    '-Dlog.level=ALL',
    '-Xms1g',
    '--add-modules=ALL-SYSTEM',
    '--add-opens', 'java.base/java.util=ALL-UNNAMED',
    '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
    '-jar', JAR_PATH,
    '-configuration', CONFIG_PATH,
    '-data', vim.fn.expand('~/.cache/nvim/workspaces_jdtls/') .. WORKSPACE_DIR 
  },
  root_dir = require('jdtls.setup').find_root({'.git', 'mvnw', 'gradlew'}),
  init_options = {    
    bundles = {"/home/nix/.config/nvim/debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-0.36.0.jar"},    
  }, 
  capabilities = capabilities
}
```
For some reason, I don't know why, the debugger doesn't start with `vscode.java.startDebugSession` command.

**Comment by s1n7ax** [comment]
Go through the [lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#jdtls) instruction and follow them.

You need to call `require'lspconfig'.jdtls.setup()` to setup JDTLS somewhere in your configuration. You need to pass the path to debug plugin to the setup method.

Here is an example from one of my old commits. You can click on **Browse Files** to view the files at the time of the commit.
https://github.com/s1n7ax/dotnvim/commit/92e7c85aa5acc6d05d05986ad9f5c39ec3301883

**Comment by lobophf** [comment]
I'll try again later and let you know if everything is working. Thanks =p

**Comment by lobophf** [comment]
I made some changes, and my debug is working now. Thanks for your help. =p
